### ISSUE TITLE
go get complains about missing gcc

### ISSUE THREAD

**Issue by jarifibrahim** [valyala/gozstd#19]
Running go get complains about missing `gcc`
```
root@ba0ab0d66064:/# go get -v github.com/valyala/gozstd
github.com/valyala/gozstd (download)
github.com/valyala/gozstd
# github.com/valyala/gozstd
exec: "gcc": executable file not found in $PATH
```
Is this expected? I thought `gcc` is not necessary since the repository already contains the `*.a` files.

**Comment by valyala** [comment]
It looks like `gcc` in required for `cgo` code :(

**Comment by jarifibrahim** [comment]
Thanks @valyala
