### ISSUE TITLE
Update to Zstd 1.5.0

### ISSUE THREAD

**Issue by jimsmart** [valyala/gozstd#35]
Hi,

I see Zstd 1.5.0 has just been released, with improved performance.

https://github.com/facebook/zstd/releases/tag/v1.5.0

I tried running `make update-zstd` in a copy of the gozstd repo - to submit a pull request - but when I committed the changes afterwards, there was only a single file that had changed. It didn't seem to have updated. I suspect there is more to this process?

Please update gozstd to use Zstd 1.5.0 - thanks!

**Comment by valyala** [comment]
`gozstd` has been updated to `zstd v1.5.0` in the commit https://github.com/valyala/gozstd/commit/f86d73fc96fedcf0d78ed906e414feaff7115018

**Comment by valyala** [comment]
This commit has been included in [gozstd v1.10.0](https://github.com/valyala/gozstd/releases/tag/v1.10.0). Closing the feature request as done.

**Comment by jimsmart** [comment]
Thanks very much, appreciated!
